language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN=84ceafc8-0e15-432b-8695-46afdd9c8326

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always